UP/Models/Job.cs
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using System.Xml.Linq;

namespace UP.Models
{
    public class Job

    {
        [Key]
        public int JobID { get; set; }

        [Display(Name = "Job Name")]
        public string Jobname { get; set; }
        [DataType(DataType.MultilineText)]
        public string JobDes { get; set; }

        public string Jobstatus { get; set; }
        public string JobCategory { get; set; }

        public decimal  JobSalary {get; set;}

        [Required]
        public DateTime? RecordCreatedOn { get; set; }

        public Category jobcat { get; set; }
        public Location joblocate { get; set; }
    }
}

UP/Controllers/JobController.cs
using UP.Data;
using UP.Models;
using Microsoft.AspNetCore.Mvc;
using UP.Migrations;

namespace UP.Controllers
{
    public class JobController : Controller
    {
        private readonly ApplicationDbContext _context;
        public JobController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            IEnumerable<Job> objCatlist = _context.Jobs;
            return View(objCatlist);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Job empobj)
        {
            if (ModelState.IsValid)
            {
                _context.Jobs.Add(empobj);
                _context.SaveChanges();
                TempData["ResultOk"] = "Record Added Successfully!";
                return RedirectToAction("Index");
            }
            return View(empobj);
        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var empfromdb = _context.Jobs.Find(id);
            if (empfromdb == null)
            {
                return NotFound();
            }
            return View(empfromdb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Job empobj)
        {
            if (ModelState.IsValid)
            {
                _context.Jobs.Update(empobj);
                _context.SaveChanges();
                TempData["ResultOk"] = "Data Updated Successfully!";
                return RedirectToAction("Index");
            }
            return View(empobj);
        }


        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var empfromdb = _context.Jobs.Find(id);
            if (empfromdb == null)
            {
                return NotFound();
            }
            return View(empfromdb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteEmp(int? id)
        {
            var deleterecord = _context.Jobs.Find(id);
            if (deleterecord == null)
            {
                return NotFound();
            }
            _context.Jobs.Remove(deleterecord);
            _context.SaveChanges();
            TempData["ResultOk"] = "Data Deleted Successfully!";
            return RedirectToAction("Index");
        }

    }
}

UP/Views/Job/Create.cshtml
@model Job


<div class="container shadow p-5">
    <div class="row pb-2">
        <h2>Add Job</h2>
    </div>

    <form method="post">
        <div asp-validation-summary="All"></div>

        <div class="form-row">
            <div class="form-group col-md-6">
                <label asp-for="Jobname">Job Name</label>
                <input type="text" class="form-control mb-3" asp-for="Jobname" placeholder="Enter Name">
                <span asp-validation-for="Jobname" class=" alert-danger"></span>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="JobDes">Job Description</label>
                <input type="text" class="form-control mb-3" asp-for="JobDes" placeholder="Enter Designation">
                <span asp-validation-for="JobDes" class=" alert-danger"></span>
            </div>
        </div>

@*        <div class="form-row">
            <div class="form-group col-md-6">
                <label asp-for="Address">Address</label>
                <input type="text" class="form-control mb-3" asp-for="Address" placeholder="Enter Address">
                <span asp-validation-for="Address" class=" alert-danger"></span>
            </div>
            <div class="form-group col-md-6 mb-3">
                <label asp-for="RecordCreatedOn">Created On</label>
                <input type="datetime-local" class="form-control" asp-for="RecordCreatedOn">
                <span asp-validation-for="RecordCreatedOn" class=" alert-danger"></span>
            </div>
        </div>*@


        <button type="submit" class="btn btn-lg btn-primary p-2"><i class="bi bi-file-plus-fill"></i>Save</button>
        <a asp-controller="Job" asp-action="Index" class="btn btn-lg btn-warning p-2">Back To List</a>
    </form>

</div>


@*//for front end validations*@

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
    }

UP/Views/Job/Index.cshtml
@model IEnumerable<Job>
<div class="container shadow p-5">

    <div class="col mb-3">
        <a asp-controller="Job" asp-action="Create" class="btn btn-lg btn-primary"><i class="bi bi-file-plus-fill"></i>Add Employee</a>
    </div>
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th scope="col">Job Name</th>
                <th scope="col">Job Description</th>
                <th scope="col">Job Category</th>
                <th scope="col">Job Salary</th>
                <th></th>
            </tr>
        </thead>
        <tbody>

            @foreach (var item in Model)
            {
                <tr>
                    <td width="20%">
                        @item.Jobname
                    </td>
                    <td width="20%">
                        @item.JobDes
                    </td>
                    <td width="25%">
                        @item.jobcat
                    </td>
                    <td width="20%">
                        @item.JobSalary
                    </td>
                    <td>
                        <div role="group" class="w-60 btn-group">
                            <a asp-controller="Job" asp-action="Edit" asp-route-id="@item.JobID" class=" btn btn-sm btn-primary"><i class="bi bi-pencil-square"></i>Edit</a>&nbsp;
                            <a asp-controller="Job" asp-action="Delete" asp-route-id="@item.JobID" class="btn btn-sm btn-danger"><i class="bi bi-trash-fill"></i>Delete</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>